sonar.projectKey=oncc-senegal-laravel
sonar.projectName=ONCC Sénégal Laravel
sonar.projectVersion=1.0

sonar.sources=app,config,database,routes,resources
sonar.tests=tests

sonar.exclusions=vendor/**,node_modules/**,storage/**,bootstrap/cache/**,public/build/**

sonar.sourceEncoding=UTF-8
